### ISSUE TITLE
No way to turn caching off or set caching location

### ISSUE THREAD

**Issue by MikeDMorgan** [MarioniLab/MouseGastrulationData#14]
The devel version of ExperimentHub has now changed such that any default cache locations give an error. We are currently using the MouseGastrulationData for one of the Milo vignettes, which is causing a package build error on R/Bioc devel. Would it be possible to allow the user to set either the cache location, or to switch off the caching, e.g. `cache=FALSE` to accommodate these sorts of changes?

**Comment by jonathangriffiths** [comment]
Thanks Mike - I was hoping that the change would just transition a user to the new database location automatically, but I guess that is only the case for new installs.

As I understand it, the failure prompts a user to change copy files across from their cache location to the new default, or to delete it. Can you give me a bit more information about what system you are on that it is not possible for either of these to be done? (or to flush the whole system if it is a build machine, or perhaps most easily to set the BFC_CACHE environment variable directly in the vignette?)

I'm pretty keen to avoid adding this feature if it is possible, because BFC is very much designed to handle this stuff without the user getting involved. Moreover, since the user would have to specify the same cache every time, I would fear some considerable data duplication on their machine.

**Comment by MikeDMorgan** [comment]
It has been deliberately setup to fail based on Lori's post on the bioc-devel list. Tbh, this is largely causing issues on the Bioc build machines which I have no control over. As a temporary fix I've set it to remove the default location in the affected vignette, and set BFC_CACHE=FALSE, but its pretty hacky. Maybe this is only temporary?

**Comment by jonathangriffiths** [comment]
Lori is hoping to have all the caches on the build machines flushed and everything back up and running over the next few days. Is that okay for your Milo issue?

As for your second point, it is well made. It would be a good idea to introduce an argument for the user to provide a BiocFileCache object (although please do not expect me to add this imminently!)

**Comment by MikeDMorgan** [comment]
No rush - I appreciate this amounts to a feature request! Thanks Jonny.
