### ISSUE TITLE
Problem with installation due to the dependency `magick`

### ISSUE THREAD

**Issue by EliHei2** [MarioniLab/MouseGastrulationData#16]
Hi! apparently there is a new dependency, `magick` added. I can't install it on my machine. The usual error:

`1: In .inet_warning(msg) :installation of package ‘magick’ had non-zero exit status`

any tricks?

**Comment by jonathangriffiths** [comment]
Hi there

Could you share the entire output of your `install` call please?

I have had issues with magick in the past on my Mac.

Jonny

**Comment by EliHei2** [comment]
Hi Jonny, so this is what I get:

```
* installing *source* package ‘magick’ ...
** package ‘magick’ successfully unpacked and MD5 sums checked
** using staged installation
Package Magick++ was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++.pc'
to the PKG_CONFIG_PATH environment variable
No package 'Magick++' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lMagick++-6.Q16
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the Magick++ library. Try installing:
 - deb: libmagick++-dev (Debian, Ubuntu)
 - rpm: ImageMagick-c++-devel (Fedora, CentOS, RHEL)
 - csw: imagemagick_dev (Solaris)
 - brew imagemagick@6 (MacOS)
For Ubuntu versions Trusty (14.04) and Xenial (16.04) use our PPA:
   sudo add-apt-repository -y ppa:cran/imagemagick
   sudo apt-get update
   sudo apt-get install -y libmagick++-dev
If Magick++ is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a Magick++.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: Magick++.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘magick’
* removing ‘/homes/elyas/anaconda3/envs/eli_env/lib/R/library/magick’
ERROR: dependency ‘magick’ is not available for package ‘SpatialExperiment’
* removing ‘/homes/elyas/anaconda3/envs/eli_env/lib/R/library/SpatialExperiment’
ERROR: dependency ‘SpatialExperiment’ is not available for package ‘MouseGastrulationData’
* removing ‘/homes/elyas/anaconda3/envs/eli_env/lib/R/library/MouseGastrulationData’
```

P.S.: I'm working on a cluster not a local machine, so installing the library is a tricky without the `sudo` access.

**Comment by jonathangriffiths** [comment]
This is a change to SpatialExperiment that is causing the pain. And indeed, it will be a pain to fix without being able to install those libraries yourself.

I would consider, probably in this order:
1. Using singularity if possible i.e. if it is installed on the cluster. You could build an image like [this](https://github.com/jonathangriffiths/MGD_playground/blob/main/images/mgd.def).
2. Ask the cluster admins to install `libmagick++`
3. Try a personal installation of linuxbrew on the cluster to see if you can get a version of `libmagick++` installed like that
4. Download the source code of `MouseGastrulationData`, scrub it off the SpatialExperiment dependencies, and then build/install that
5. Install MGD on your laptop, download the data, and then move it to the cluster with scp, rsync etc.
6. Build an old version of R on the cluster that will support an older Bioconductor version from before the SpatialExperiment changes, if indeed this magick one has only appeared recently. Or, even just use a version of MGD from before I included the spatial data.

Since SpatialExperiment appears to be the sanctioned format for Bioconductor going forwards I'm not going to be able to remove that dependency. You could consider asking them about this problem, especially if it is common, as they may be able to find an easier-to-install replacement.

Let me know how you get on,
Jonny
